- iextrading4j-all/pom.xml
- iextrading4j-api/pom.xml
- iextrading4j-client/pom.xml
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/socket/IOSocketFactory.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/socket/IOSocketImpl.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/socket/WebSocket.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/socket/listener/DataReceiver.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/socket/model/AsyncRequest.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/socket/model/LastAsyncRequest.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/socket/model/MarketAsyncRequest.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/socket/model/TOPSAsyncRequest.java
- iextrading4j-client/src/test/java/pl/zankowski/iextrading4j/client/socket/model/AsyncRequestTest.java
- iextrading4j-client/src/test/java/pl/zankowski/iextrading4j/client/socket/model/IOSocketFactoryTest.java
- iextrading4j-samples/pom.xml
- iextrading4j-samples/src/main/java/pl/zankowski/iextrading4j/samples/AsyncSubscriptionExample.java
- pom.xml
> Prepare to ver 1.0.2 release

- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/stocks/KeyStats.java
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/stocks/Quote.java
Hi Wojciech,
These are the changes we discussed.  Please merge these in and then run the unit tests as one is still failing that I couldn't figure out why.
Thanks,
Mike.
> Added missing JSON properties to Stock API

- .travis.yml
- pom.xml
> Add build for jdk 12

- CHANGELOG.md
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/account/MessageCutoffRequestBuilder.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/account/PayAsYouGoRequestBuilder.java
- iextrading4j-client/src/test/java/pl/zankowski/iextrading4j/client/rest/request/account/MessageCutoffRequestBuilderTest.java
- iextrading4j-client/src/test/java/pl/zankowski/iextrading4j/client/rest/request/account/PayAsYouGoRequestBuilderTest.java
- iextrading4j-samples/src/main/java/pl/zankowski/iextrading4j/sample/iexcloud/rest/AccountSample.java
- iextrading4j-test/src/test/java/pl/zankowski/iextrading4j/test/rest/v1/BaseIEXCloudV1ServiceTest.java
- iextrading4j-test/src/test/java/pl/zankowski/iextrading4j/test/rest/v1/account/MessageCutoffServiceTest.java
- iextrading4j-test/src/test/java/pl/zankowski/iextrading4j/test/rest/v1/account/PayAsYouGoServiceTest.java
- iextrading4j-test/src/test/java/pl/zankowski/iextrading4j/test/rest/v1/refdata/IsinServiceTest.java
- iextrading4j-test/src/test/resources/__files/rest/v1/account/MessageCutoffResponse.json
- iextrading4j-test/src/test/resources/__files/rest/v1/account/PayAsYouGoResponse.json
> Account endpoints

- CHANGELOG.md
- README.md
- iextrading4j-acceptance/pom.xml
- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/v1/StocksAcceptanceTest.java
- iextrading4j-all/pom.xml
- iextrading4j-api/pom.xml
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/stocks/ChartRange.java
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/stocks/Quote.java
- iextrading4j-api/src/test/java/pl/zankowski/iextrading4j/api/stocks/QuoteTest.java
- iextrading4j-client/pom.xml
- iextrading4j-samples/pom.xml
- iextrading4j-test/pom.xml
- iextrading4j-test/src/test/java/pl/zankowski/iextrading4j/test/rest/stock/QuoteServiceTest.java
- iextrading4j-test/src/test/resources/__files/rest/stock/QuoteResponse.json
- pom.xml
> Update to newest api

- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/alternative/SentimentEvent.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/sse/request/alternative/SentimentSseRequestBuilder.java
- iextrading4j-client/src/test/java/pl/zankowski/iextrading4j/client/sse/request/alternative/SentimentSseRequestBuilderTest.java
- iextrading4j-samples/src/main/java/pl/zankowski/iextrading4j/sample/iexcloud/sse/SseAlternativeSample.java
Sentiment SSE response return type does not conform with the provided schema.
Fixes #  https://github.com/WojciechZankowski/iextrading4j/issues/68
> fix regarding https://github.com/WojciechZankowski/iextrading4j/issues/68

- CHANGELOG.md
- README.md
- iextrading4j-acceptance/pom.xml
- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/v1/ForexAcceptanceTest.java
- iextrading4j-all/pom.xml
- iextrading4j-api/pom.xml
- iextrading4j-api/src/test/java/pl/zankowski/iextrading4j/api/alternative/SentimentEventTest.java
- iextrading4j-client/pom.xml
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/sse/request/forex/CurrencyRatesSseRequestBuilder.java
- iextrading4j-client/src/test/java/pl/zankowski/iextrading4j/client/sse/request/forex/CurrencyRatesSseRequestBuilderTest.java
- iextrading4j-samples/pom.xml
- iextrading4j-samples/src/main/java/pl/zankowski/iextrading4j/sample/iexcloud/sse/SseForexSample.java
- iextrading4j-test/pom.xml
- pom.xml
> Add SSE forex endpoint

- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/v1/AlternativeAcceptanceTest.java
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/alternative/Sentiment.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/alternative/AbstractSentimentRequestBuilder.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/alternative/DailySentimentRequestBuilder.java
- iextrading4j-client/src/test/java/pl/zankowski/iextrading4j/client/rest/request/alternative/DailySentimentRequestBuilderTest.java
- iextrading4j-samples/src/main/java/pl/zankowski/iextrading4j/sample/iexcloud/rest/AlternativeSample.java
> Create daily Sentiment request builder

- .gitignore
- CHANGELOG.md
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/datapoint/TimeSeriesRequestBuilder.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/stocks/EarningsRequestBuilder.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/stocks/v1/AbstractLastStocksRequestBuilder.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/stocks/v1/BalanceSheetRequestBuilder.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/stocks/v1/CashFlowRequestBuilder.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/stocks/v1/EstimatesRequestBuilder.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/stocks/v1/FinancialsRequestBuilder.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/stocks/v1/IncomeStatementRequestBuilder.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/sse/request/forex/CurrencyRatesSseRequestBuilder.java
- iextrading4j-client/src/test/java/pl/zankowski/iextrading4j/client/rest/request/datapoint/TimeSeriesRequestBuilderTest.java
- iextrading4j-client/src/test/java/pl/zankowski/iextrading4j/client/rest/request/stocks/EarningsRequestBuilderTest.java
- iextrading4j-client/src/test/java/pl/zankowski/iextrading4j/client/sse/request/forex/CurrencyRatesSseRequestBuilderTest.java
- iextrading4j-samples/src/main/java/pl/zankowski/iextrading4j/sample/iexcloud/sse/SseForexSample.java
> IEX Cloud update

- README.md
- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/v1/ForexAcceptanceTest.java
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/forex/CurrencyConversion.java
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/forex/CurrencyRate.java
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/forex/HistoricalCurrencyRate.java
- iextrading4j-api/src/test/java/pl/zankowski/iextrading4j/api/forex/CurrencyConversionTest.java
- iextrading4j-api/src/test/java/pl/zankowski/iextrading4j/api/forex/CurrencyRateTest.java
- iextrading4j-api/src/test/java/pl/zankowski/iextrading4j/api/forex/HistoricalCurrencyRateTest.java
- iextrading4j-test/src/test/java/pl/zankowski/iextrading4j/test/rest/v1/forex/LatestCurrencyRatesServiceTest.java
- iextrading4j-test/src/test/resources/__files/rest/v1/forex/LatestCurrencyRatesResponse.json
> Fix iex cloud build

- CHANGELOG.md
- README.md
- iextrading4j-acceptance/pom.xml
- iextrading4j-all/pom.xml
- iextrading4j-api/pom.xml
- iextrading4j-client/pom.xml
- iextrading4j-samples/pom.xml
- iextrading4j-test/pom.xml
- pom.xml
> Release new version

- iextrading4j-acceptance/pom.xml
- iextrading4j-api/pom.xml
- iextrading4j-client/pom.xml
- iextrading4j-test/pom.xml
- pom.xml
> Fix sonar coverage

- .travis.yml
- iextrading4j-acceptance/pom.xml
- iextrading4j-api/pom.xml
- iextrading4j-client/pom.xml
- iextrading4j-mutation/pom.xml
- iextrading4j-test/pom.xml
- pom.xml
- scripts/deploy.sh
> Javadoc deploy

- CHANGELOG.md
- README.md
- iextrading4j-acceptance/pom.xml
- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/v1/AlternativeAcceptanceTest.java
- iextrading4j-all/pom.xml
- iextrading4j-api/pom.xml
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/stocks/v1/Dividends.java
- iextrading4j-api/src/test/java/pl/zankowski/iextrading4j/api/stocks/v1/DividendsTest.java
- iextrading4j-client/pom.xml
- iextrading4j-mutation/pom.xml
- iextrading4j-samples/pom.xml
- iextrading4j-test/pom.xml
- iextrading4j-test/src/test/java/pl/zankowski/iextrading4j/test/rest/v1/stock/DividendsServiceTest.java
- iextrading4j-test/src/test/resources/__files/rest/v1/stock/DividendsResponse.json
- pom.xml
> Release 3.3.4

- .travis.yml
- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/MarketAcceptanceTest.java
- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/v1/StocksAcceptanceTest.java
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/stocks/v1/Split.java
- iextrading4j-api/src/test/java/pl/zankowski/iextrading4j/api/stocks/v1/SplitTest.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/rest/request/market/MarketRequestBuilder.java
- iextrading4j-test/src/test/java/pl/zankowski/iextrading4j/test/rest/v1/stock/SplitsServiceTest.java
- iextrading4j-test/src/test/resources/__files/rest/v1/stock/SplitsResponse.json
> Add date to Splits

- .travis.yml
- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/MarketAcceptanceTest.java
- iextrading4j-api/pom.xml
- iextrading4j-client/pom.xml
> Fix maven build

- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/IEXTradingApiVersion.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/IEXTradingClient.java
- iextrading4j-client/src/main/java/pl/zankowski/iextrading4j/client/properties/PropertyType.java
Simply added the production url and sandbox url for the STABLE version of the apis
> ADD-STABLE Adidtion of production and sandbox url for stable version

- CHANGELOG.md
- README.md
- iextrading4j-acceptance/pom.xml
- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/v1/StocksAcceptanceTest.java
- iextrading4j-all/pom.xml
- iextrading4j-api/pom.xml
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/stocks/v1/Dividends.java
- iextrading4j-api/src/test/java/pl/zankowski/iextrading4j/api/stocks/v1/DividendsTest.java
- iextrading4j-client/pom.xml
- iextrading4j-mutation/pom.xml
- iextrading4j-samples/pom.xml
- iextrading4j-test/pom.xml
- iextrading4j-test/src/test/java/pl/zankowski/iextrading4j/test/rest/v1/stock/DividendsServiceTest.java
- pom.xml
> Release 3 4 0

- CHANGELOG.md
- README.md
- iextrading4j-acceptance/pom.xml
- iextrading4j-all/pom.xml
- iextrading4j-api/pom.xml
- iextrading4j-api/src/main/java/pl/zankowski/iextrading4j/api/refdata/v1/SymbolDescription.java
- iextrading4j-api/src/test/java/pl/zankowski/iextrading4j/api/refdata/v1/SymbolDescriptionTest.java
- iextrading4j-client/pom.xml
- iextrading4j-mutation/pom.xml
- iextrading4j-samples/pom.xml
- iextrading4j-test/pom.xml
- pom.xml
> Update search prod model

- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/v1/CorporateActionsAcceptanceTest.java
- iextrading4j-acceptance/src/test/java/pl/zankowski/iextrading4j/test/acceptance/v1/DataPointsAcceptanceTest.java
> Fix the build
